# Syntax Highligthing using the BAT command.
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Aliases
#alias ll='ls -lAFh'
alias ll='exa --long -all --icons'
alias repos='cd $HOME/git/'
alias zshrc='nvim $HOME/.zshrc'
alias lg='lazygit'

# this will fix the issue:  Backspace producing space on command line #597
TERM=xterm
eval "$(starship init zsh)"
