# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Syntax Highligthing using the BAT command.
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# PATH for LVIM
export PATH=/Users/piktonus97m/.local/bin:$PATH
# Default Editor
export EDITOR="lvim"

# Aliases
#alias ll='ls -lAFh'
alias ll='exa --long -all --icons'
alias repos='cd $HOME/git/'
alias zshrc='nvim $HOME/.zshrc'
alias lg='lazygit'
alias cat='bat'

# this will fix the issue:  Backspace producing space on command line #597
TERM=xterm
eval "$(starship init zsh)"
