[tools]
bat = "latest"
chezmoi = "latest"
zoxide = "latest" 
neovim = "latest"
lazygit = "latest"
fastfetch= "latest"
eza = "latest"
fzf = "latest"
delta = "latest"
fd = "latest"
ripgrep = "latest"
starship = "latest"
