# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"
# Syntax Highligthing using the BAT command.
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
PS1="%K{blue}%n@%m%k %B%F{cyan}%(4~|...|)%3~%F{white} %# %b%f%k"



# Set variables

# Change zsh options

# Aliases
#alias ll='ls -lAFh'
alias ll='exa --long -all --icons'
alias ic='ibmcloud'
alias secrets='cd $HOME/Documents/git/.secrets'
alias repos='cd $HOME/Documents/git/'
alias vim='lvim'
alias ctx='kubectx'
alias ctxg='kubectx | grep -i'
alias zshrc='nvim $HOME/.zshrc'
alias lg='lazygit'
alias tmux="TERM=screen-256color-bce tmux"

# The following alias and functions wont work for you. Please ignore them. 
## List Begins ##

# APIS
alias cat-mes-api='cat $HOME/Documents/git/.secrets/keys/mes-api-key'
alias cat-cross-api='cat $HOME/Documents/git/.secrets/keys/cross-tower-login-api-key'
alias cat-talent-api='cat $HOME/Documents/git/.secrets/keys/talent-login-api-key'
alias cat-l2c-api='cat $HOME/Documents/git/.secrets/keys/l2c-api-key'

# Add Locations to $PATH Variable

# Functions
function mkcd(){
  mkdir -p "$@" && cd "$_";
}

# IC Login Functions
function ic-prod(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/cross-tower-login-api-key)
	ic login -u apikey -p $loginKey
}

function ic-talent(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/talent-login-api-key)
	ic login -u apikey -p $loginKey
}

function ic-mes(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/mes-api-key)
	ic login -u apikey -p $loginKey
}

function ic-l2c(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/l2c-api-key)
	ic login -u apikey -p $loginKey
}

# OC Login Functions
function oc-prod(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/cross-tower-login-api-key)
	oc login -u apikey -p $loginKey
}

function oc-talent(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/talent-login-api-key)
	oc login -u apikey -p $loginKey
}

function oc-mes(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/mes-api-key)
	oc login -u apikey -p $loginKey
}

function oc-l2c(){
	loginKey=$(cat $HOME/Documents/git/.secrets/keys/l2c-api-key)
	oc login -u apikey -p $loginKey
}

## List Ends ##

# Other Stuff

# This activate IBM Cloud Autocompletion after installation. 
source /usr/local/ibmcloud/autocomplete/zsh_autocomplete
export PATH="/usr/local/opt/kubernetes-cli@1.22/bin:$PATH"


## ZSH Native Configuration

# Use modern completion sytem
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
#eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd's

# this will fix the issue:  Backspace producing space on command line #597

TERM=xterm

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
