# Syntax Highligthing using the BAT command.
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PATH=$PATH:~/.local/bin #aca se encuentra lunarvim entonces hay que agregarlo en el path

PS1="%K{blue}%n@%m%k %B%F{cyan}%(4~|...|)%3~%F{white} %# %b%f%k"

# Aliases

#alias ll='ls -lAFh'
alias ll='exa --long -all --icons'
alias repos='cd $HOME/Documents/git/'
alias vim='lvim'
alias zshrc='nvim $HOME/.zshrc'
alias lg='lazygit'
alias tmux="TERM=screen-256color-bce tmux"
alias dot='cd $HOME/Documents/git/dotfiles'

# Add Locations to $PATH Variable

# Functions
function mkcd(){
  mkdir -p "$@" && cd "$_";
}

## ZSH Native Configuration

# Use modern completion sytem
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
#eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd's

# this will fix the issue:  Backspace producing space on command line #597

TERM=xterm
