# MacOS specific configuration

# Default Editor
export EDITOR="nvim"

# Aliases

alias ll='lsd -l'
alias tree='lsd --tree'
alias repos='cd $HOME/git/'
alias zshrc='nvim $HOME/.zshrc'
alias lg='lazygit'
alias cat='bat'
alias ctx='kubectx'
alias k='kubectl'

# this will fix the issue:  Backspace producing space on command line #597
TERM=xterm
eval "$(starship init zsh)"

[[ "$TERM_PROGRAM" == "CodeEditApp_Terminal" ]] && . "/Applications/CodeEdit.app/Contents/Resources/codeedit_shell_integration.zsh"

## Work related configuration
export PATH=/Users/francisco.sanabria/Library/Python/3.9/bin:$PATH ### GROOT CONFIGURATION
export PATH=/Users/francisco.sanabria/.local/bin:$PATH

