# MacOS specific configuration

#PATH for JetBrain Tools
# I would like to create a ENV variable to avoid confusion on the work machine vs personal machine
export PATH=/Users/francisco.sanabria/Library/Application\ Support/JetBrains/Toolbox/scripts:$PATH

# Default Editor
export EDITOR="nvim"

# Aliases

alias ll='exa --long -all --icons --no-user'
alias repos='cd $HOME/git/'
alias zshrc='nvim $HOME/.zshrc'
alias lg='lazygit'
alias cat='bat'
alias ctx='kubectx'
alias notes='cd /Users/francisco.sanabria/Library/Mobile\ Documents/com~apple~CloudDocs/Archive\ Notes'
# this will fix the issue:  Backspace producing space on command line #597
TERM=xterm
eval "$(starship init zsh)"

[[ "$TERM_PROGRAM" == "CodeEditApp_Terminal" ]] && . "/Applications/CodeEdit.app/Contents/Resources/codeedit_shell_integration.zsh"
